import os

def make_wps_namelist(start_year,start_month,start_day,end_year,end_month,end_day):
	start_hour = '06:00:00'
	end_hour   = '06:00:00'
	wps_start_date= str(start_year)+'-'+str(start_month).zfill(2)+'-'+str(start_day).zfill(2)+'_'+ start_hour
	wps_end_date  = str(end_year)  +'-'+str(end_month).zfill(2)  +'-'+str(end_day).zfill(2)  +'_'+ end_hour
	wps_file = open('namelist.wps',"wb")

	wps_template =      ( \
				"&share\n"
				"wrf_core = 'ARW',\n"
				"max_dom = 1,\n"
				"start_date  = "+wps_start_date+ ",'2000-01-24_00:00:00',\n"
				"end_date    = "+wps_end_date+ ",'2000-01-24_12:00:00',\n"
				"interval_seconds = 10800,\n"
				"io_form_geogrid = 2,\n"
				'/\n\n'

				"&geogrid\n"
				"parent_id = 1, 1,\n"
				"parent_grid_ratio = 1, 3,\n"
				"i_parent_start = 1, 31\n"
				"j_parent_start = 1, 17\n"
				"e_we = 260,112\n"
				"e_sn = 310,97\n"
				"geog_data_res = '10m','2m',\n"
				"dx = 4000,\n"
				"dy = 4000,\n"
				"map_proj  = 'lambert',\n"
				"ref_lat   = 43.249\n"
				"ref_lon   = -88.454\n"
				"truelat1  = 43.249,\n"
				"truelat2  = 43.249,\n"
				"stand_lon = -88.454\n"
				"geog_data_path = '/Users/mabdioskouei/WRFDIR/geog'\n"
				'/ \n\n'

				"&ungrib\n"
				"out_format = 'WPS',\n"
				"prefix = 'FILE',\n"
				'/\n\n'

				"&metgrid\n"
				"fg_name = './FILE'\n"
				"io_form_metgrid = 2,\n"
				"/\n"
				)
	wps_file.write(wps_template)
	wps_file.close()
	print (\
		"\n******************************************************\n"
		"namelist.wps is created with:\n" 
		"start_date  = "+wps_start_date+ "\n"
		"end_date    = "+wps_end_date+ "\n" 
		"******************************************************\n\n")

def make_wrf_namelist(start_year,start_month,start_day,end_year,end_month,end_day):
	start_hour = '06:00:00'
	end_hour   = '06:00:00'
	wrf_start_date= str(start_year)+'-'+str(start_month).zfill(2)+'-'+str(start_day).zfill(2)+'_'+ start_hour
	wrf_end_date  = str(end_year)  +'-'+str(end_month).zfill(2)  +'-'+str(end_day).zfill(2)  +'_'+ end_hour
	wrf_file = open('namelist.input',"wb")
	wrf_template =      ( \
				"&time_control\n"
				"run_days                            = 2,\n"
				"run_hours                           = 00,\n"
				"run_minutes                         = 0,\n"
				"run_seconds                         = 0,\n"
				"start_year                          = "+start_year+",    2014\n"
				"start_month                         = "+start_month+",  07\n"
				"start_day                           = "+start_day+",  24\n"
				"start_hour                          = 06,  00\n"
				"start_minute                        = 00,  00\n"
				"start_second                        = 00,  00\n"
				"end_year                            = "+end_year+",    2014\n"
				"end_month                           = "+end_month+",  08\n"
				"end_day                             = "+end_day+",  18\n"
				"end_hour                            = 06,  12\n"
				"end_minute                          = 00,  00\n"
				"end_second                          = 00,  00\n"
				"interval_seconds                    = 10800,\n"
				"input_from_file                     = .true.,.true.,.false.,\n"
				"history_interval                    = 60,  60,   60,\n"
				"frames_per_outfile                  = 1, 1, 1,\n"
				"restart                             = .false.,\n"
				"restart_interval                    = 1440,\n"
				"io_form_history                     = 2,\n"
				"io_form_restart                     = 2,\n"
				"io_form_input                       = 2,\n"
				"io_form_boundary                    = 2,\n"
				"io_form_auxinput2                   = 2,\n"
				"io_form_auxinput4                   = 0,\n"
				"io_form_auxinput5                   = 2,\n"
				"io_form_auxinput6                   = 0,\n"
				"io_form_auxinput7                   = 0,\n"
				"auxinput4_interval_m                = 0, 360, 360,\n"
				"auxinput5_interval_m                = 60, 60,  60,\n"
				"auxinput7_interval_m                = 60, 60, 60,\n"
				"auxinput4_inname                    = \"wrflowinp_d<domain>\",\n"
				"auxinput5_inname                    = \"wrfchemi_<hour>_d<domain>\",\n"
				"auxinput6_inname                    = \"wrfbiochemi_d<domain>\",\n"
				"auxinput7_inname                    = \"wrffirechemi_d<domain>_<date>\",\n"
				"frames_per_auxinput5                = 12, 12,\n"
				"frames_per_auxinput7                = 1, 1,\n"
				"debug_level                         = 0,\n"
				"/\n"
				"&dfi_control\n"
				"/\n"
				"&domains\n"
				"time_step                           = 30,\n"
				"time_step_fract_num                 = 0,\n"
				"time_step_fract_den                 = 1,\n"
				"max_dom                             = 1,\n"
				"e_we                                = 260,    319,\n"
				"e_sn                                = 310,    193,\n"
				"e_vert                              = 53,    53,\n"
				"num_metgrid_levels                  = 32,\n"
				"num_metgrid_soil_levels             = 4,\n"
				"dx                                  =  4000,  3333.33,\n"
				"dy                                  =  4000,  3333.33,\n"
				"grid_id                             = 1,     2,\n"
				"parent_id                           = 1,     1,\n"
				"i_parent_start                      = 1,     79,\n"
				"j_parent_start                      = 1,     57,\n"
				"parent_grid_ratio                   = 1,     3,\n"
				"parent_time_step_ratio              = 1,     3,\n"
				"feedback                            = 0,\n"
				"smooth_option                       = 0,\n"
				"p_top_requested                     = 5000\n"
				"zap_close_levels                    = 50\n"
				"interp_type                         = 1\n"
				"t_extrap_type                       = 2\n"
				"force_sfc_in_vinterp                = 0\n"
				"use_levels_below_ground             = .true.\n"
				"use_surface                         = .true.\n"
				"lagrange_order                      = 1\n"
				"sfcp_to_sfcp                        = .true.\n"
				"eta_levels                          = 1.0000, 0.9940, 0.9880, 0.9820, 0.9750,0.9680, 0.9560, 0.9440, 0.9320, 0.9200,0.9020, 0.8790, 0.8560, 0.8330, 0.8100, 0.7870, 0.7600, 0.7330, 0.7060, 0.6730,0.6400, 0.6070, 0.5740, 0.5410, 0.5080,0.4750, 0.4420, 0.4090, 0.3820, 0.3550, 0.3330, 0.3110, 0.2890, 0.2670, 0.2450, 0.2240, 0.2030, 0.1820, 0.1614, 0.1412, 0.1220, 0.1050, 0.0890, 0.0750, 0.0625, 0.0520, 0.0425, 0.0335, 0.0250, 0.0175, 0.0110, 0.0050, 0.0000\n"
				"/\n"
				"&physics\n"
				"mp_physics                          = 10,     10,     10,\n"
				"progn                               = 0,     1,     1,\n"
				"naer                                = 1e9,      1e9,      1e9,\n"
				"ra_lw_physics                       = 4,     4,     4,\n"
				"ra_sw_physics                       = 2,     2,     2,\n"
				"radt                                = 5,     5,     5,\n"
				"sf_sfclay_physics                   = 5,     5,     2,\n"
				"sf_surface_physics                  = 1,     1,     2,\n"
				"bl_pbl_physics                      = 6,     6,     2,\n"
				"bldt                                = 0,     0,     0,\n"
				"mp_zero_out                         = 2,\n"
				"mp_zero_out_thresh                  = 1.e-8,\n"
				"cu_physics                          = 3,     3,     0,\n"
				"cudt                                = 0,     0,     0,\n"
				"cu_diag                             = 1,\n"
				"cugd_avedx                          = 0,\n"
				"isfflx                              = 1,\n"
				"ifsnow                              = 1,\n"
				"icloud                              = 1,\n"
				"surface_input_source                = 1,\n"
				"num_soil_layers                     = 4,\n"
				"sf_urban_physics                    = 0,\n"
				"maxiens                             = 1,\n"
				"maxens                              = 3,\n"
				"maxens2                             = 3,\n"
				"maxens3                             = 16,\n"
				"ensdim                              = 144,\n"
				"sst_update                          = 0,\n"
				"cu_rad_feedback                     = .true.,  .true.,  .false.,\n"
				"num_land_cat                       = 24\n"
				"/\n"
				"&fdda\n"
				"/\n"
				"&dynamics\n"
				"w_damping                           = 1,\n"
				"diff_opt                            = 1,1\n"
				"km_opt                              = 4,\n"
				"diff_6th_opt                        = 0,      0,      0,\n"
				"diff_6th_factor                     = 0.08,   0.12,   0.12,\n"
				"base_temp                           = 290.\n"
				"damp_opt                            = 0,\n"
				"zdamp                               = 5000.,  5000.,  5000.,\n"
				"dampcoef                            = 0.02,    0.2,    0.2\n"
				"khdif                               = 0,      0,      0,\n"
				"kvdif                               = 0,      0,      0,\n"
				"non_hydrostatic                     = .true., .true., .true.,\n"
				"tke_adv_opt                         = 1,      1,      1,\n"
				"moist_adv_opt                       = 2,      2,      2,\n"
				"scalar_adv_opt                      = 2,      2,      2,\n"
				"chem_adv_opt                        = 2,      2,      2,\n"
				"tracer_adv_opt                      = 2,      2,      2,\n"
				"tracer_opt                          = 0,\n"
				"/\n"
				"&bdy_control\n"
				"spec_bdy_width                      = 5,\n"
				"spec_zone                           = 1,\n"
				"relax_zone                          = 4,\n"
				"specified                           = .true., .false.,.false.,\n"
				"nested                              = .false., .true., .true.,\n"
				"/\n"
				"&grib2\n"
				"/\n"
				"&chem\n"
				"kemit                               = 19,\n"
				"chem_opt                            = 107, 107\n"
				"bioemdt                             = 10,30\n"
				"photdt                              = 10,30\n"
				"chemdt                              = 2.00,1.00\n"
				"io_style_emissions                  = 1,\n"
				"emiss_opt                           = 3,          3,\n"
				"emiss_inpt_opt                      = 1,          1,\n"
				"chem_in_opt                         = 0,          0,\n"
				"phot_opt                            = 2,          2,\n"
				"gas_drydep_opt                      = 1,          1,\n"
				"aer_drydep_opt                      = 1,          1,\n"
				"bio_emiss_opt                       = 0,          0,\n"
				"dust_opt                            = 0,\n"
				"dmsemis_opt                         = 0,\n"
				"seas_opt                            = 0,\n"
				"gas_bc_opt                          = 1,          1,\n"
				"gas_ic_opt                          = 1,          1,\n"
				"aer_bc_opt                          = 1,          1,\n"
				"aer_ic_opt                          = 1,          1,\n"
				"gaschem_onoff                       = 1,          1,\n"
				"aerchem_onoff                       = 1,          1,\n"
				"wetscav_onoff                       = 0,          0,\n"
				"cldchem_onoff                       = 0,          0,\n"
				"vertmix_onoff                       = 1,          1,\n"
				"chem_conv_tr                        = 1,          1,\n"
				"biomass_burn_opt                    = 0,          0,\n"
				"plumerisefire_frq                   = 0,         0,\n"
				"have_bcs_chem                       = .true., .false.,\n"
				"aer_ra_feedback                     = 0,\n"
				"aer_op_opt                          = 1,\n"
				"opt_pars_out                        = 0,\n"
				"diagnostic_chem                     = 0,\n"
				"/\n"
				"&namelist_quilt\n"
				"nio_tasks_per_group = 0,\n"
				"nio_groups = 1,\n"
				"/\n"
				)
	wrf_file.write(wrf_template)
	wrf_file.close()
	print (\
		"\n******************************************************\n"
		"namelist.wrf is created with:\n" 
		"start_date  = "+wrf_start_date+ "\n"
		"end_date    = "+wrf_end_date+ "\n" 
		"******************************************************\n\n")


